number_list =[]
answer = int(input("Ask for a number"))
number_list.append(answer)
answer = int(input("Ask for a number"))
number_list.append(answer)
answer = int(input("Ask for a number"))
number_list.append(answer)
answer = int(input("Ask for a number"))
number_list.append(answer)
answer = int(input("Ask for a number"))
number_list.append(answer)
avg = sum(number_list)/len(number_list)
print("The average is", avg)